// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtznisoktpsfhljgkkre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0em5pc29rdHBzZmhsamdra3JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyOTc4MTIsImV4cCI6MjA2MDg3MzgxMn0.AAa2W_7S-exZKJGb4LRQ1LNmmiHOVJf_aQGSXTFYykw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);